### PR TITLE
Support dotnet aspire

### PR DESCRIPTION
**Pull request by odero**

### CODE REVIEW

**Comment by habbes** [comment]
Thanks for this PR @odero. It should save a lot of setup headache.

**Comment by habbes** [comment]
Got a couple of errors trying to run this locally in Visual Studio. Let me try the running the suggested commands and see if it will work.

image

**Comment by habbes** [comment]
After fumbling around with different commands and resources, what seemed to finally work was running `dotnet workload install aspire`.

Now I'm able to run the project and it launches the dashboard. Makes life much easier, and makes it easier to monitor logs from different projects in one place.

**Comment by habbes** [comment]
Looking into how deployment will work. Currently the different components are deployed separately. The API and frontend are deployed automatically when we merge to main (Which is why I haven't merged the PR cause it might break "prod" if deployment is not correctly handled).

I've looked up some examples of how to deploy Aspire apps. I think the quickest way would be to figure out how to deploy and run components independently. The main thing to figure out is how the server and runner will figure out the production Redis endpoint now that that explicit configuration has been removed from the code.

**Comment by odero** [comment]
I'll take a stab at it and see how things play out

**Comment by habbes** [comment]
@odero I generated an ["aspire manifest"](https://learn.microsoft.com/en-us/dotnet/aspire/deployment/manifest-format) and found that it uses the following environment variable to inject the connection string: `ConnectionStrings__sharpbench-cache`. If configure that on the servers I believe deployment should work. I test this locally by running the server project in isolation with and without setting that connection string, it crashes with an exception when that configuration is not set.

**Comment by habbes** [comment]
Turns out Azure App Service environment variables don't like hyphens and Aspire resource names don't like underscores. Maybe will switch the service names to camelCase or PascalCase.

**Pull request merged**
